Fix compatibility with sqlite3 before v3.35
The language feature `RETURNING` was added to sqlite3 in release v3.35.
See https://www.sqlite.org/draft/lang_returning.html

Thus the recent switch to `asyncpg` (commit 18ef939a04f) broke compatibility
with sqlite3 before v3.35.
The resulting exception was:
```
sqlite3.OperationalError: near "RETURNING": syntax error
```

Simply removing the `RETURNING (id)` suffix of the query fixes the issues
for such an older versions of sqlite3.

Situation of distributions:
* Debian Bullseye: v3.34
* Ubuntu Focal (LTS): v3.31
* Ubuntu Impish: v3.35

Thus only the most recent (non-LTS) release of Ubuntu supports this new
keyword at the moment.